default_language_version:
   python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
  -   id: check-added-large-files
  -   id: check-yaml
  -   id: check-toml
      args:
      - --unsafe
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
    -   id: pyupgrade
        args:
        - --py39-plus
        - --keep-runtime-typing
-   repo: https://github.com/charliemarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black